process_data.py - transform input data to koji builds (nvrs), handles cross koji/brew imports
fedora-modularity/whatpkgs pull request #1
Opened 2016-09-29 09:34 UTC by lkocman

Hi Stephen,

this isn't the most effective tool but it does the job.
Some usage example:

$ ./process_data.py --help
Usage: process_data.py [options]

Options:
  -h, --help            show this help message and exit
  --builds-from-file=BUILDS_FROM_FILE
  --find-missing-builds
                        Checks whether builds are present in given koji
                        instance
  --print-builds        Prints builds in a koji-compat format
  --import-builds       Import builds
  --import-threads=IMPORT_THREADS
                        Import threads (default is 4)
  --koji-profile=KOJI_PROFILE
  --koji-dest-profile=KOJI_DEST_PROFILE
                        profile of Koji import-target
  --workdir=WORKDIR     This is required for import of builds
  --debug               Print debug info such as individual rpm imports

./process_data.py --koji-profile koji-stage --builds-from-file sampledata/selfhosting-source-packages-full.txt --find-missing | tee sampledata/selfhosting-source-packages-missing.txt

./process_data.py --koji-profile koji --koji-dest-profile koji-stage  --builds-from-file sampledata/selfhosting-source-packages-missing.txt --import-builds --workdir /tmp/kojistg.import-base-runtime

2016-09-29 18:49 UTC, sgallagher requested changes
The `--help` contents are useful, but they don't explain why you would want to do any of these things. Would you mind creating a README? I think I can work it out, but I'd rather just have a reference.

2016-10-03 12:16 UTC, lkocman commented
Hello Stephen, will do :-) I actually used this script for bootstraping koji-stage. We'll use the same for bootstrap any other instance of koji. Since it works cross-env e.g. koji.prod -> koji.stage -> internal koji.stage -> internal-koji.prod

2016-10-03 13:10 UTC, lkocman commented
Does this look better Stephen?

2016-10-03 13:15 UTC, sgallagher commented
At a first glance, it does indeed look much better. Thanks! I'll give it a more thorough review later today.

2016-10-05 18:22 UTC, merged